version = 1

test_patterns = ["*.py"]

exclude_patterns = [
    "__pycache__/",
    "*.py[cod]",
    "*$py.class"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
